### ISSUE TITLE
Dates are changing after sending from getServerSideProps to the page component (NextJS)

### ISSUE THREAD

**Issue by DanniloSN** [blitz-js/superjson#130]
The Birth date of a person is saved as: "2001-01-05 00: 00: 00.000", and it can be checked if print just after you get the data inside the getServerSideProps. But when you try to print the same data inside the component, the date is going to be an object with different values: "Date Thu Jan 04 2001 22:00:00 GMT-0200 (Brasilia Summer Time)", it reduced the time by 2 hours, and I need it to be the exactly as saved. What can I do about it?

**Comment by Skn0tt** [comment]
The dates refer to the same exact instant, but in different timezones. The server-side one is in UTC, while the second is in the timezone of your browser (-2hrs Brasilia Summer TIme). You'll need to factor in the local timezone, e.g. using `.getTimezoneOffset()`.

AFAIK, there's no way to set the timezone for a `Date` object, which restrains SuperJSON from preserving it.

On a related note: Storing birth dates as `Date` has its problems, because JavaScript's `Date` type always has the notion of a timezone, which does not exist for birth dates - they have no time! The [temporal proposal](https://tc39.es/proposal-temporal/docs/), currently in Stage 3, introduces `PlainDate` which might be a better fit. Until that's wide-spread, strings like `"2001-01-05"` seem to be an acceptable replacement.
