### ISSUE TITLE
Serialize Error?

### ISSUE THREAD

**Issue by hasparus** [blitz-js/superjson#74]
Hi folks! I thought I'll drop this small feature request.

The dreamlike thing I'd like to do is deserializing backend error and throwing it to a React ErrorBoundary.

Currently I get this:

> SerializableError: Error serializing `.json.error` returned from `getServerSideProps` in "/meetings".
> Reason: `object` ("[object Error]") cannot be serialized as JSON. Please only return JSON serializable data types.

**Comment by Skn0tt** [comment]
As a workaround, you should be able to use `registerClass`, as shown here https://github.com/blitz-js/superjson/issues/69#issuecomment-702302533, or `registerCustom`, as show show here https://github.com/blitz-js/superjson/pull/71.

This is currently undocumented because we want to know about the ways people are using this.

Considering that `Error` is available across all JS implementations, I'll take a look at how we can add default support for this to `superjson`.

**Comment by hasparus** [comment]
Thanks!

**Comment by Skn0tt** [comment]
@allcontributors add hasparus for ideas
